### ISSUE TITLE
update for hubot-slack adapter v3

### ISSUE THREAD

**Issue by shokai** [shokai/hubot-rss-reader#21]
http://pasero.net/~mako/blog/s/689

**Comment by shokai** [comment]
np

**Comment by shokai** [comment]
```
2015-01-09T02:49:49.412162+00:00 app[web.1]: Fri, 09 Jan 2015 02:49:49 GMT hubot-rss-reader:rss-checker fetch http://feeds.delicious.com/v2/rss/miyagawa
2015-01-09T02:49:49.601465+00:00 app[web.1]: Fri, 09 Jan 2015 02:49:49 GMT hubot-rss-reader:rss-checker statusCode: 503
2015-01-09T02:49:49.879830+00:00 app[web.1]: Fri, 09 Jan 2015 02:49:49 GMT hubot-rss-reader TypeError: Cannot call method 'send' of undefined
2015-01-09T02:49:49.879837+00:00 app[web.1]:   at SlackBot.send (/app/node_modules/hubot-slack/src/slack.coffee:181:17)
2015-01-09T02:49:49.879839+00:00 app[web.1]:   at Robot.messageRoom (/app/node_modules/hubot/src/robot.coffee:409:5)
2015-01-09T02:49:49.879840+00:00 app[web.1]:   at RSSChecker.<anonymous> (/app/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:61:15)
2015-01-09T02:49:49.879842+00:00 app[web.1]:   at RSSChecker.emit (events.js:95:17)
2015-01-09T02:49:49.879844+00:00 app[web.1]:   at /app/node_modules/hubot-rss-reader/libs/rss-checker.coffee:113:12
2015-01-09T02:49:49.879846+00:00 app[web.1]:   at tryCatch1 (/app/node_modules/hubot-rss-reader/node_modules/bluebird/js/main/util.js:45:21)
2015-01-09T02:49:49.879847+00:00 app[web.1]:   at Promise._callHandler (/app/node_modules/hubot-rss-reader/node_modules/bluebird/js/main/promise.js:597:13)
2015-01-09T02:49:49.879849+00:00 app[web.1]:   at Promise._settlePromiseFromHandler (/app/node_modules/hubot-rss-reader/node_modules/bluebird/js/main/promise.js:607:18)
2015-01-09T02:49:49.879851+00:00 app[web.1]:   at Promise._settlePromiseAt (/app/node_modules/hubot-rss-reader/node_modules/bluebird/js/main/promise.js:769:18)
2015-01-09T02:49:49.879852+00:00 app[web.1]:   at Async._drainQueue (/app/node_modules/hubot-rss-reader/node_modules/bluebird/js/main/async.js:98:12)
2015-01-09T02:49:49.879853+00:00 app[web.1]:   at Async._drainQueues (/app/node_modules/hubot-rss-reader/node_modules/bluebird/js/main/async.js:103:10)
2015-01-09T02:49:49.879855+00:00 app[web.1]:   at Async.drainQueues (/app/node_modules/hubot-rss-reader/node_modules/bluebird/js/main/async.js:37:14)
2015-01-09T02:49:49.879856+00:00 app[web.1]:   at process._tickCallback (node.js:442:13)
2015-01-09T02:49:49.879858+00:00 app[web.1]:
2015-01-09T02:49:49.880309+00:00 app[web.1]: Fri, 09 Jan 2015 02:49:49 GMT hubot-rss-reader wait 600 seconds
```

**Comment by shokai** [comment]
cannot call `robot.messageRoom` after crawl feeds.

**Comment by shokai** [comment]
slack-adapter was crashed when `robot.send` to non-existent channel/room.
wrapped with try-catch.
