### ISSUE TITLE
dont work with irc

### ISSUE THREAD

**Issue by Jaglag** [shokai/hubot-rss-reader#22]
like the topic say:

[13:16:09] [~Jaglag]: !rss add http://feeds.feedburner.com/blogspot/rkEL
[13:16:18] [~Jaglag]: !rss add http://postillion.soup.io/
[13:17:15] [~Jaglag]: !rss add http://golem.de.dynamic.feedsportal.com/pf/578068/http://rss.golem.de/rss.php?feed=RSS2.0
[13:17:27] [~Jaglag]: Butlerz rss register http://golem.de.dynamic.feedsportal.com/pf/578068/http://rss.golem.de/rss.php?feed=RSS2.0
[13:17:35] [~Jaglag]: Butlerz rss add http://golem.de.dynamic.feedsportal.com/pf/578068/http://rss.golem.de/rss.php?feed=RSS2.0
[13:19:08] [~Jaglag]: !rss list
[13:19:08] [@Butlerz]: nothing

here the heroku logs:

2015-01-06T12:17:18.310925+00:00 app[web.1]: [Tue Jan 06 2015 12:17:18 GMT+0000 (UTC)] ERROR TypeError: Object http://go
lem.de.dynamic.feedsportal.com/pf/578068/http://rss.golem.de/rss.php?feed=RSS2.0 has no method 'then'
2015-01-06T12:17:18.310928+00:00 app[web.1]:   at TextListener.callback (/app/node_modules/hubot-rss-reader/scripts/hubo
t-rss-reader.coffee:67:5, <js>:81:52)
2015-01-06T12:17:18.310930+00:00 app[web.1]:   at TextListener.Listener.call (/app/node_modules/hubot/src/listener.coffe
e:27:7, <js>:23:14)
2015-01-06T12:17:18.310931+00:00 app[web.1]:   at Robot.receive (/app/node_modules/hubot/src/robot.coffee:197:9, <js>:14
2:33)
2015-01-06T12:17:18.310952+00:00 app[web.1]:   at IrcBot.Adapter.receive (/app/node_modules/hubot/src/adapter.coffee:66:
5, <js>:47:25)
2015-01-06T12:17:18.310954+00:00 app[web.1]:   at Client.<anonymous> (/app/node_modules/hubot-irc/src/irc.coffee:257:7,
<js>:342:21)
2015-01-06T12:17:18.310955+00:00 app[web.1]:   at Client.emit (events.js:106:17)
2015-01-06T12:17:18.310957+00:00 app[web.1]:   at Client.<anonymous> (/app/node_modules/hubot-irc/node_modules/irc/lib/i
rc.js:471:22)
2015-01-06T12:17:18.310958+00:00 app[web.1]:   at Client.emit (events.js:95:17)
2015-01-06T12:17:18.310960+00:00 app[web.1]:   at /app/node_modules/hubot-irc/node_modules/irc/lib/irc.js:658:22
2015-01-06T12:17:18.310962+00:00 app[web.1]:   at Array.forEach (native)
2015-01-06T12:17:18.310963+00:00 app[web.1]:   at Socket.<anonymous> (/app/node_modules/hubot-irc/node_modules/irc/lib/i
rc.js:655:15)
2015-01-06T12:17:18.310964+00:00 app[web.1]:   at Socket.emit (events.js:95:17)
2015-01-06T12:17:18.310966+00:00 app[web.1]:   at Socket.<anonymous> (_stream_readable.js:765:14)
2015-01-06T12:17:18.310969+00:00 app[web.1]:   at Socket.emit (events.js:92:17)
2015-01-06T12:17:18.310970+00:00 app[web.1]:   at emitReadable_ (_stream_readable.js:427:10)
2015-01-06T12:17:18.310973+00:00 app[web.1]:   at readableAddChunk (_stream_readable.js:166:9)
2015-01-06T12:17:18.310971+00:00 app[web.1]:   at emitReadable (_stream_readable.js:423:5)
2015-01-06T12:17:18.310974+00:00 app[web.1]:   at Socket.Readable.push (_stream_readable.js:128:10)
2015-01-06T12:17:18.310976+00:00 app[web.1]:   at TCP.onread (net.js:529:21)
2015-01-06T12:17:18.311233+00:00 app[web.1]: [Tue Jan 06 2015 12:17:18 GMT+0000 (UTC)] DEBUG Message 'Butlerz rss add ht
tp://golem.de.dynamic.feedsportal.com/pf/578068/http://rss.golem.de/rss.php?feed=RSS2.0' matched regex //./i/
2015-01-06T12:17:18.310977+00:00 app[web.1]:
2015-01-06T12:18:51.403110+00:00 app[web.1]: [Tue Jan 06 2015 12:18:51 GMT+0000 (UTC)] DEBUG From Jaglag to #butlerz: !r
ss list
2015-01-06T12:18:51.404178+00:00 app[web.1]: [Tue Jan 06 2015 12:18:51 GMT+0000 (UTC)] DEBUG Message '!rss list' matched

**Comment by patrys** [comment]
I had the same problem when using old CoffeeScript package. Did you not skip this installation step?

```
npm install coffee-script@">=1.8.0" -save
```

**Comment by Jaglag** [comment]
hah that fixxed it tyvm!

**Comment by shokai** [comment]
:beers:
