### ISSUE TITLE
TypeError occured

### ISSUE THREAD

**Issue by cutmail** [shokai/hubot-rss-reader#28]
When I add feed in local environment, TypeError occured.

```sh
Hubot> hubot rss add https://github.com/shokai.atom
[Sun Feb 01 2015 12:07:39 GMT+0900 (JST)] INFO hubot-rss-reader: add https://github.com/shokai.atom
[Sun Feb 01 2015 12:07:39 GMT+0900 (JST)] ERROR TypeError: Object https://github.com/shokai.atom has no method 'then'
  at TextListener.callback (/Users/cutmail/src/hubot/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:97:5, <js>:134:52)
  at TextListener.Listener.call (/Users/cutmail/src/hubot/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Users/cutmail/src/hubot/node_modules/hubot/src/robot.coffee:197:9, <js>:142:33)
  at Shell.Adapter.receive (/Users/cutmail/src/hubot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at Interface.<anonymous> (/Users/cutmail/src/hubot/node_modules/hubot/src/adapters/shell.coffee:56:15, <js>:100:23)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:203:10)
  at Interface._line (readline.js:532:8)
  at Interface._ttyWrite (readline.js:761:14)
  at ReadStream.onkeypress (readline.js:100:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1096:12)
  at ReadStream.onData (readline.js:841:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:765:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at ReadStream.Readable.push (_stream_readable.js:128:10)
  at TTY.onread (net.js:529:21)
```

**Comment by shokai** [comment]
please install coffee-script 1.8

    % npm install coffee-script@">=1.8.0" -save
