### ISSUE TITLE
ERROR TypeError: undefined is not a function

### ISSUE THREAD

**Issue by GrantStreetGroup** [shokai/hubot-rss-reader#39]
I'm getting this when I start my hubot up..  
It's running in a docker container.

    Thu, 06 Aug 2015 17:17:34 GMT hubot-rss-reader checker start
    [Thu Aug 06 2015 13:17:34 GMT-0400 (EDT)] ERROR TypeError: undefined is not a function
      at run (/opt/archie/hubot/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:73:7, <js>:92:35)
      at Brain.<anonymous> (/opt/archie/hubot/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:82:5, <js>:101:14)
      at Brain.g (events.js:199:16)
      at Brain.emit (events.js:129:20)
      at Brain.set (/opt/archie/hubot/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
      at robotStore (/opt/archie/hubot/node_modules/hubot-react/scripts/react.js:228:22)
      at start (/opt/archie/hubot/node_modules/hubot-react/scripts/react.js:262:3)
      at Brain.<anonymous> (/opt/archie/hubot/node_modules/hubot-react/scripts/react.js:313:5)
      at Brain.<anonymous> (/opt/archie/hubot/node_modules/hubot-react/node_modules/underscore/underscore.js:831:21)
      at Brain.g (events.js:199:16)
      at Brain.emit (events.js:129:20)
      at Brain.mergeData (/opt/archie/hubot/node_modules/hubot/src/brain.coffee:92:5, <js>:82:19)
      at /opt/archie/hubot/node_modules/hubot-redis-brain/src/redis-brain.coffee:49:9, <js>:28:23
      at try_callback (/opt/archie/hubot/node_modules/hubot-redis- brain/node_modules/redis/index.js:548:9)
      at RedisClient.return_reply (/opt/archie/hubot/node_modules/hubot-redis-brain/node_modules/redis/index.js:630:13)
      at ReplyParser.<anonymous> (/opt/archie/hubot/node_modules/hubot-redis-brain/node_modules/redis/index.js:282:14)
      at ReplyParser.emit (events.js:107:17)
      at ReplyParser.send_reply (/opt/archie/hubot/node_modules/hubot-redis-brain/node_modules/redis/lib/parser/javascript.js:300:10)
      at ReplyParser.execute (/opt/archie/hubot/node_modules/hubot-redis-brain/node_modules/redis/lib/parser/javascript.js:203:22)
      at RedisClient.on_data (/opt/archie/hubot/node_modules/hubot-redis-brain/node_modules/redis/index.js:504:27)
      at Socket.<anonymous> (/opt/archie/hubot/node_modules/hubot-redis-brain/node_modules/redis/index.js:82:14)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

Any ides what is going on?

**Comment by shokai** [comment]
please update coffee-script

    npm install coffee-script@">=1.8.0" -save

**Comment by davidleong-lithium** [comment]
I am getting the same error for my docker container which has coffee-script 1.10.0 (latest)
