### ISSUE TITLE
RSSChecker doesn't work with hubot-mongodb-brain

### ISSUE THREAD

**Issue by ghost** [shokai/hubot-rss-reader#51]
When I run hubot-rss-reader with hubot-mongodb-brain, I get

```
[Tue May 31 2016 10:53:21 GMT+0900 (JST)] INFO MongoDB connected
  hubot-rss-reader checker start +0ms
[Tue May 31 2016 10:53:21 GMT+0900 (JST)] ERROR TypeError: Cannot call method 'then' of undefined
  at run (/home/<username>/hubot/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:74:7, <js>:94:35)
  at Brain.<anonymous> (/home/<username>/hubot/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:83:5, <js>:103:14)
  at Brain.g (events.js:180:16)
  at Brain.emit (events.js:95:17)
  at Brain.mergeData (/home/<username>/hubot/node_modules/hubot/src/brain.coffee:92:5, <js>:82:19)
  at /home/<username>/hubot/node_modules/hubot-mongodb-brain/scripts/hubot-mongodb-brain.coffee:47:9, <js>:41:23
  at handleCallback (/home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/lib/utils.js:96:12)
  at /home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/lib/cursor.js:839:16
  at handleCallback (/home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
  at setCursorNotified (/home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:511:3)
  at /home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:582:16
  at queryCallback (/home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
  at [object Object].Callbacks.emit (/home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
  at [object Object].messageHandler (/home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:371:23)
  at Socket.<anonymous> (/home/<username>/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:301:22)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:765:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)
```

It's not reproducible when using file-brain.coffee.

**Comment by ghost** [comment]
sorry, duplicate #39.
