### ISSUE TITLE
ERROR TypeError: undefined is not a function

### ISSUE THREAD

**Issue by davidleong-lithium** [shokai/hubot-rss-reader#53]
I've been unable to use hubot-rss-reader with mongodb.  I get the same error as #39 and #51 but I am already running coffeescript v1.10.0

> hubot@chat:~$ coffee --version
> CoffeeScript version 1.10.0

```
[Sun Jun 05 2016 19:38:41 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'then' of undefined
  at run (/home/hubot/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:74:7, <js>:94:34)
  at Brain.<anonymous> (/home/hubot/node_modules/hubot-rss-reader/scripts/hubot-rss-reader.coffee:83:5, <js>:103:14)
  at Brain.g (events.js:199:16)
  at Brain.emit (events.js:107:17)
  at Brain.mergeData (/home/hubot/node_modules/hubot/src/brain.coffee:92:5, <js>:82:19)
  at /home/hubot/node_modules/hubot-mongodb-brain/scripts/hubot-mongodb-brain.coffee:47:9, <js>:41:23
  at handleCallback (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/lib/utils.js:96:12)
  at /home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/lib/cursor.js:839:16
  at handleCallback (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
  at setCursorDeadAndNotified (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:501:3)
  at nextFunction (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:652:7)
  at [object Object].Cursor.next [as _next] (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:693:3)
  at fetchDocs (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/lib/cursor.js:835:10)
  at /home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/lib/cursor.js:858:7
  at handleCallback (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
  at nextFunction (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
  at /home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
  at queryCallback (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
  at [object Object].Callbacks.emit (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
  at [object Object].messageHandler (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
  at Socket.<anonymous> (/home/hubot/node_modules/hubot-mongodb-brain/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)

```

**Comment by Ulrar** [comment]
I have the same error :(

Okay, solved, you do actually need the specific version of cofeescript. My bad.

**Comment by gburgett** [comment]
Added a pull request for this issue - #55
